plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE
  - docs/*.md
exclude:
  - src
  - spaces
  - ci
  - tests
  - client
  - data
  - cloud