version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - python/install-packages:
          app-dir: reqs_optional
          pip-dependency-file: requirements_optional_8bit.txt
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest tests --junit-xml=test-results/test_report.xml
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: test-results
workflows:
  main:
    jobs:
      - build-and-test
